module.exports = [
    // "https://docs.rakwireless.com/product-categories/wisduo/rak3172-module/datasheet/",
    // "https://docs.rakwireless.com/product-categories/wisduo/rak11720-module/datasheet/",
    // "https://docs.rakwireless.com/product-categories/wisduo/rak4630-module/datasheet/",
    // "https://docs.rakwireless.com/product-categories/wislink/rak2287/datasheet/",
    // "https://docs.rakwireless.com/product-categories/wislink/rak5146/datasheet/",
    // "https://docs.rakwireless.com/product-categories/wisblock/rak4631-r/overview/",
    // "https://docs.rakwireless.com/product-categories/wisblock/rak19007/datasheet/",
    // "https://docs.rakwireless.com/product-categories/wisblock/rak1901/datasheet/",
    // "https://docs.rakwireless.com/product-categories/wisblock/rak1902/datasheet/",
    // "https://docs.rakwireless.com/product-categories/wisblock/rak1903/datasheet/",
    // "https://docs.rakwireless.com/product-categories/wisblock/rak1904/datasheet/",
    // "https://docs.rakwireless.com/product-categories/wisblock/rak1906/datasheet/",
    // "https://docs.rakwireless.com/product-categories/wisblock/rak5801/datasheet/",
    // "https://docs.rakwireless.com/product-categories/wisblock/rak12001/datasheet/",
    // "https://docs.rakwireless.com/product-categories/wisblock/rak12003/datasheet/",
    // "https://docs.rakwireless.com/product-categories/wisblock/rak12004/datasheet/",
    // "https://docs.rakwireless.com/product-categories/wisblock/rak12500/datasheet/",
    // "https://docs.rakwireless.com/product-categories/wisblock/rak12006/datasheet/",
    // "https://docs.rakwireless.com/product-categories/wisblock/rak12007/datasheet/",
    // "https://docs.rakwireless.com/product-categories/wisblock/rak12009/datasheet/",
    // "https://docs.rakwireless.com/product-categories/wisblock/rak12010/datasheet/",
    // "https://docs.rakwireless.com/product-categories/wisblock/rak12011/datasheet/",
    // "https://docs.rakwireless.com/product-categories/wisblock/rak12012/datasheet/",
    // "https://docs.rakwireless.com/product-categories/wisblock/rak12013/datasheet/",
    // "https://docs.rakwireless.com/product-categories/wisblock/rak12014/datasheet/",
    // "https://docs.rakwireless.com/product-categories/wisblock/rak12015/datasheet/",
    // "https://docs.rakwireless.com/product-categories/wisblock/rak12016/datasheet/",
    // "https://docs.rakwireless.com/product-categories/wisblock/rak12017/datasheet/",
    // "https://docs.rakwireless.com/product-categories/wisblock/rak12033/datasheet/",
    // "https://docs.rakwireless.com/product-categories/wisblock/rak12034/datasheet/",
    // "https://docs.rakwireless.com/product-categories/wisblock/rak12047/datasheet/",
    // "https://docs.rakwireless.com/product-categories/wisblock/rak12025/datasheet/",
    // "https://docs.rakwireless.com/product-categories/wisblock/rak12021/datasheet/",
    // "https://docs.rakwireless.com/product-categories/wisblock/rak12037/datasheet/",
    // "https://docs.rakwireless.com/product-categories/wisblock/rak12027/datasheet/",
    // "https://docs.rakwireless.com/product-categories/wisblock/rak12052/datasheet/",
    // "https://docs.rakwireless.com/product-categories/wisblock/rak12022/datasheet/",
    // "https://docs.rakwireless.com/product-categories/wisblock/rak12039/datasheet/",
    // "https://docs.rakwireless.com/product-categories/wisblock/rak13002/datasheet/",
    // "https://docs.rakwireless.com/product-categories/wisblock/rak14000/datasheet/",
    // "https://docs.rakwireless.com/product-categories/wisblock/rak13800/datasheet/",
    // "https://docs.rakwireless.com/product-categories/wisblock/rak19001/datasheet/",
    // "https://docs.rakwireless.com/product-categories/wisblock/rak4631/datasheet/",
    // "https://docs.rakwireless.com/product-categories/wisblock/rak1921/datasheet/",
    // "https://docs.rakwireless.com/product-categories/wisblock/rak19011/datasheet/",
    // "https://docs.rakwireless.com/product-categories/wisblock/rak19012/datasheet/",
    // "https://docs.rakwireless.com/product-categories/wisblock/rak19017/datasheet/",
    // "https://docs.rakwireless.com/product-categories/wisblock/rak19016/datasheet/",
    // "https://docs.rakwireless.com/product-categories/wisblock/rak19003/datasheet/",
    // "https://docs.rakwireless.com/product-categories/wisblock/rak19009/datasheet/",
    // "https://docs.rakwireless.com/product-categories/wisblock/rak19010/datasheet/",
    // "https://docs.rakwireless.com/product-categories/wisblock/rak11200/datasheet/",
    "https://docs.rakwireless.com/product-categories/wisgate/rak7289v2/datasheet"

]

